/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria_proyecto;

/**
 *
 * @author snakt
 */
public class CarpetaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Carpeta
     */
    public CarpetaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int Mediana=80, Grande=120, Familiar=150, total=0,CantidadHM=0, CantidadHG=0,CantidadHF=0,
            CantidadTotal=0,CantidadMM=0 ,CantidadMG=0 , CantidadMF=0 ,CantidadPM=0,CantidadPG=0,CantidadPF=0
            ,CantidadCoca=0, CantidadSprite=0, CantidadManzanita=0, CantidadPapas=0;
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRbHawainaMediana = new javax.swing.JRadioButton();
        jRbHawainaGrande = new javax.swing.JRadioButton();
        jRbHawainaFamiliar = new javax.swing.JRadioButton();
        jRbMexicanaMediana = new javax.swing.JRadioButton();
        jRbMexicanaGrande = new javax.swing.JRadioButton();
        jRbMexicanaFamiliar = new javax.swing.JRadioButton();
        jRbPepeMediana = new javax.swing.JRadioButton();
        jRbPepeGrande = new javax.swing.JRadioButton();
        jRbPepeFamiliar = new javax.swing.JRadioButton();
        jRbRefrescoManzanita = new javax.swing.JRadioButton();
        jRbRefrescoSprite = new javax.swing.JRadioButton();
        jRbRefrescoCoca = new javax.swing.JRadioButton();
        jRbPapas = new javax.swing.JRadioButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("espacio");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 870, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        jLabel5.setText("$ 80");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel6.setText("$ 120");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel7.setText("$ 150");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel20.setText("$ 80");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel21.setText("$ 120");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jLabel22.setText("$ 150");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel23.setText("$ 80");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        jLabel24.setText("$ 120");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        jLabel25.setText("$ 150");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImgPizza/hqdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel27.setText("jLabel1");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel17.setText("$ 18");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        jLabel16.setText("$ 15");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jLabel15.setText("$ 20");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLabel18.setText("papas");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        jLabel19.setText("$ 25");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 630, 10));

        jRbHawainaMediana.setText("Mediana");
        jRbHawainaMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbHawainaMedianaActionPerformed(evt);
            }
        });
        getContentPane().add(jRbHawainaMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jRbHawainaGrande.setText("Grande");
        getContentPane().add(jRbHawainaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jRbHawainaFamiliar.setText("Familiar");
        getContentPane().add(jRbHawainaFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jRbMexicanaMediana.setText("Mediana");
        getContentPane().add(jRbMexicanaMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jRbMexicanaGrande.setText("Grande");
        getContentPane().add(jRbMexicanaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jRbMexicanaFamiliar.setText("Familiar");
        jRbMexicanaFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbMexicanaFamiliarActionPerformed(evt);
            }
        });
        getContentPane().add(jRbMexicanaFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jRbPepeMediana.setText("Mediana");
        getContentPane().add(jRbPepeMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jRbPepeGrande.setText("Grande");
        getContentPane().add(jRbPepeGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        jRbPepeFamiliar.setText("Familiar");
        getContentPane().add(jRbPepeFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jRbRefrescoManzanita.setText("Manzanita");
        getContentPane().add(jRbRefrescoManzanita, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jRbRefrescoSprite.setText("Sprite");
        getContentPane().add(jRbRefrescoSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jRbRefrescoCoca.setText("Coca Cola");
        jRbRefrescoCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbRefrescoCocaActionPerformed(evt);
            }
        });
        getContentPane().add(jRbRefrescoCoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jRbPapas.setText("A la franceza");
        getContentPane().add(jRbPapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, -1, -1));

        jButtonRegresar.setText("Regresar");
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        jButtonCancelar.setText("Cancelar");
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, -1, -1));

        jButtonAceptar.setText("Aceptar");
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRbHawainaMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbHawainaMedianaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRbHawainaMedianaActionPerformed

    private void jRbRefrescoCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbRefrescoCocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbRefrescoCocaActionPerformed

    private void jRbMexicanaFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbMexicanaFamiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbMexicanaFamiliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarpetaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRbHawainaFamiliar;
    private javax.swing.JRadioButton jRbHawainaGrande;
    private javax.swing.JRadioButton jRbHawainaMediana;
    private javax.swing.JRadioButton jRbMexicanaFamiliar;
    private javax.swing.JRadioButton jRbMexicanaGrande;
    private javax.swing.JRadioButton jRbMexicanaMediana;
    private javax.swing.JRadioButton jRbPapas;
    private javax.swing.JRadioButton jRbPepeFamiliar;
    private javax.swing.JRadioButton jRbPepeGrande;
    private javax.swing.JRadioButton jRbPepeMediana;
    private javax.swing.JRadioButton jRbRefrescoCoca;
    private javax.swing.JRadioButton jRbRefrescoManzanita;
    private javax.swing.JRadioButton jRbRefrescoSprite;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
