/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria_proyecto;

import javax.swing.JTextField;

/**
 *
 * @author snakt
 */
public class CarpetaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Carpeta
     */
    public CarpetaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int Mediana=80, Grande=120, Familiar=150, total=0,CantidadHM=0, CantidadHG=0,CantidadHF=0,
            CantidadTotal=0,CantidadMM=0 ,CantidadMG=0 , CantidadMF=0 ,CantidadPM=0,CantidadPG=0,CantidadPF=0
            ,CantidadCoca=0, CantidadSprite=0, CantidadManzanita=0, CantidadPapas=0,TotalHM=0,TotalHG=0
            ,TotalHF=0,TotalMM=0,TotalMG=0,TotalMF=0,TotalM=0,TotalPM=0,TotalPG=0,TotalPF=0,TotalPapa=0,CantidadPapa=0
            ,Papa=30,TotalCoca=0,Coca=20,TotalSprite=0,Sprite=18,TotalManzanita=0,Manzanita=15;
    String PizzaHM=null,PizzaHG=null, PizzaHF=null;
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCbFamiliarH = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jCbGrandeH = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jCbFamiliarM = new javax.swing.JComboBox<>();
        jCbGrandeM = new javax.swing.JComboBox<>();
        jCbMedianaM = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jCbFamiliarP = new javax.swing.JComboBox<>();
        jCbGrandeP = new javax.swing.JComboBox<>();
        jCbMedianaP = new javax.swing.JComboBox<>();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBGenerarTiket = new javax.swing.JButton();
        Papas = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Salida = new javax.swing.JTextField();
        jCbMedianaH = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jCbRefrescoC = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jCbRefrescoSprite = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jCbRefrescoManzanita = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel11.setText("jLabel8");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel12.setText("jLabel8");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jCbFamiliarH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbFamiliarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbFamiliarHActionPerformed(evt);
            }
        });
        jPanel4.add(jCbFamiliarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel9.setText("jLabel9");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel13.setText("jLabel13");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel28.setText("jLabel28");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jCbGrandeH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbGrandeH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbGrandeHMouseClicked(evt);
            }
        });
        jCbGrandeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbGrandeHActionPerformed(evt);
            }
        });
        jPanel4.add(jCbGrandeH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel29.setText("jLabel9");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel30.setText("jLabel13");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel31.setText("jLabel28");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jCbFamiliarM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbFamiliarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbFamiliarMActionPerformed(evt);
            }
        });
        jPanel4.add(jCbFamiliarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jCbGrandeM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbGrandeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbGrandeMActionPerformed(evt);
            }
        });
        jPanel4.add(jCbGrandeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jCbMedianaM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbMedianaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbMedianaMActionPerformed(evt);
            }
        });
        jPanel4.add(jCbMedianaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel32.setText("jLabel9");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jLabel33.setText("jLabel13");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel34.setText("jLabel28");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jCbFamiliarP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbFamiliarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbFamiliarPActionPerformed(evt);
            }
        });
        jPanel4.add(jCbFamiliarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jCbGrandeP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbGrandeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbGrandePActionPerformed(evt);
            }
        });
        jPanel4.add(jCbGrandeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jCbMedianaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbMedianaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbMedianaPActionPerformed(evt);
            }
        });
        jPanel4.add(jCbMedianaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });
        jPanel4.add(jBAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jBCancelar.setText("Cancelar");
        jPanel4.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jBGenerarTiket.setText("Generar Ticket");
        jBGenerarTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarTiketActionPerformed(evt);
            }
        });
        jPanel4.add(jBGenerarTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        Papas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        Papas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapasActionPerformed(evt);
            }
        });
        jPanel4.add(Papas, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        jLabel47.setText("jLabel9");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        jLabel48.setText("jLabel8");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        jPanel4.add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        jCbMedianaH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        jCbMedianaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbMedianaHActionPerformed(evt);
            }
        });
        jPanel4.add(jCbMedianaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 30, -1));

        jTabbedPane2.addTab("Pizzas", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("jLabel9");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jCbRefrescoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jCbRefrescoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbRefrescoCActionPerformed(evt);
            }
        });
        jPanel5.add(jCbRefrescoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel38.setText("jLabel8");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jCbRefrescoSprite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jCbRefrescoSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbRefrescoSpriteActionPerformed(evt);
            }
        });
        jPanel5.add(jCbRefrescoSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel39.setText("jLabel8");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel40.setText("jLabel9");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jCbRefrescoManzanita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jCbRefrescoManzanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbRefrescoManzanitaActionPerformed(evt);
            }
        });
        jPanel5.add(jCbRefrescoManzanita, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLabel43.setText("jLabel8");
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel44.setText("jLabel9");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jTabbedPane2.addTab("Refrescos", jPanel5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCbGrandeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbGrandeHActionPerformed
         // TODO add your handling code here:
       int nump;
        nump = jCbGrandeH.getSelectedIndex();
         TotalHG = Grande*nump;
        CantidadHG=nump;
        total=+total+TotalHG;
        CantidadTotal=+CantidadTotal+CantidadHG;
        if(nump>0)
            //es para saber el nombre del producto si no se comopro nada no se asigna nada
            PizzaHM=("Pizza Hawaiana Mediana");
    }//GEN-LAST:event_jCbGrandeHActionPerformed

    private void jCbFamiliarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbFamiliarHActionPerformed
         // TODO add your handling code here:
        int nump= jCbFamiliarH.getSelectedIndex();
        TotalHF=Familiar*nump;
        CantidadHF=nump;
        total=+total+TotalHF;
        CantidadTotal=CantidadTotal+CantidadHF;
        PizzaHG=("Pizza Hawaiana Grande");
    }//GEN-LAST:event_jCbFamiliarHActionPerformed

    private void jCbMedianaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbMedianaMActionPerformed
         // TODO add your handling code here:
        int nump= jCbMedianaM.getSelectedIndex();
        TotalMM=Mediana*nump;
        CantidadMM=nump;
        total=+total+TotalMM;
        CantidadTotal=CantidadTotal+CantidadMM;
        PizzaHF=("Pizza Hawaiana Familiar");
    }//GEN-LAST:event_jCbMedianaMActionPerformed

    private void jCbGrandeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbGrandeMActionPerformed
         // TODO add your handling code here:
       int nump=jCbGrandeM.getSelectedIndex();
        TotalMG=Grande*nump;
        CantidadMG=nump;
        total=+total+TotalMG;
        CantidadTotal=CantidadTotal+CantidadMG;
    }//GEN-LAST:event_jCbGrandeMActionPerformed

    private void jCbFamiliarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbFamiliarMActionPerformed
         // TODO add your handling code here:
        int nump=jCbFamiliarM.getSelectedIndex();
        TotalMF=Familiar*nump;
        CantidadMF=nump;
        total=+total+TotalMF;
        CantidadTotal=CantidadTotal+CantidadMF;
    }//GEN-LAST:event_jCbFamiliarMActionPerformed

    private void jCbMedianaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbMedianaPActionPerformed
         // TODO add your handling code here:
        int nump=jCbMedianaP.getSelectedIndex();
        TotalPM=Mediana*nump;
        CantidadPM=nump;
        total=+total+TotalPM;
        CantidadTotal=CantidadTotal+CantidadPM;
    }//GEN-LAST:event_jCbMedianaPActionPerformed

    private void jCbGrandePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbGrandePActionPerformed
         // TODO add your handling code here:
        int nump=jCbGrandeP.getSelectedIndex();
        TotalPG=Grande*nump;
        CantidadPG=nump;
        total=+total+TotalPG;
        CantidadTotal=CantidadTotal+CantidadPG;
    }//GEN-LAST:event_jCbGrandePActionPerformed

    private void jCbFamiliarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbFamiliarPActionPerformed
         // TODO add your handling code here:
        int nump=jCbFamiliarP.getSelectedIndex();
        TotalPF=Mediana*nump;
        CantidadPF=nump;
        total=+total+TotalPF;
        CantidadTotal=CantidadTotal+CantidadPF;
    }//GEN-LAST:event_jCbFamiliarPActionPerformed

    private void PapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapasActionPerformed
         // TODO add your handling code here:
         int nump=Papas.getSelectedIndex();
        TotalPapa=Papa*nump;
        CantidadPapa=nump;
        total=+total+TotalPapa;
        CantidadTotal=CantidadTotal+CantidadPapa;
    }//GEN-LAST:event_PapasActionPerformed

    private void jCbRefrescoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbRefrescoCActionPerformed
        int nump= jCbRefrescoC.getSelectedIndex();
        TotalCoca=Coca*nump;
        CantidadCoca=nump;
        total=+total+TotalCoca;
        CantidadTotal=CantidadTotal+CantidadCoca;        // TODO add your handling code here:
    }//GEN-LAST:event_jCbRefrescoCActionPerformed

    private void jCbRefrescoSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbRefrescoSpriteActionPerformed
         // TODO add your handling code here:
       int  nump=jCbRefrescoSprite.getSelectedIndex();
        TotalSprite=Sprite*nump;
        CantidadSprite=nump;
        total=+total+TotalSprite;
        CantidadTotal=CantidadTotal+CantidadSprite;
    }//GEN-LAST:event_jCbRefrescoSpriteActionPerformed

    private void jCbRefrescoManzanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbRefrescoManzanitaActionPerformed
         // TODO add your handling code here:
       int  nump=jCbRefrescoManzanita.getSelectedIndex();
        TotalManzanita=Manzanita*nump;
        CantidadManzanita=nump;
        total=+total+TotalManzanita;
        CantidadTotal=CantidadTotal+CantidadManzanita;
    }//GEN-LAST:event_jCbRefrescoManzanitaActionPerformed

    private void jCbGrandeHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbGrandeHMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_jCbGrandeHMouseClicked

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
        System.out.println("el valor es: "+CantidadTotal);
    }//GEN-LAST:event_SalidaActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
        Salida.setText("Cantidad total "+CantidadTotal);
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jCbMedianaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbMedianaHActionPerformed
         // TODO add your handling code here:
         int  nump=jCbMedianaH.getSelectedIndex();
         TotalHM=Mediana*nump;
        CantidadHM=nump;
        total=+total+TotalHM;
        CantidadTotal=CantidadTotal+CantidadHM;
    }//GEN-LAST:event_jCbMedianaHActionPerformed

    private void jBGenerarTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarTiketActionPerformed
         // TODO add your handling code here:
         this.setVisible(false);
        TicketMostrador newFrame= new TicketMostrador();
        newFrame.setVisible(true);
    }//GEN-LAST:event_jBGenerarTiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarpetaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarpetaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Papas;
    private javax.swing.JTextField Salida;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGenerarTiket;
    private javax.swing.JComboBox<String> jCbFamiliarH;
    private javax.swing.JComboBox<String> jCbFamiliarM;
    private javax.swing.JComboBox<String> jCbFamiliarP;
    private javax.swing.JComboBox<String> jCbGrandeH;
    private javax.swing.JComboBox<String> jCbGrandeM;
    private javax.swing.JComboBox<String> jCbGrandeP;
    private javax.swing.JComboBox<String> jCbMedianaH;
    private javax.swing.JComboBox<String> jCbMedianaM;
    private javax.swing.JComboBox<String> jCbMedianaP;
    private javax.swing.JComboBox<String> jCbRefrescoC;
    private javax.swing.JComboBox<String> jCbRefrescoManzanita;
    private javax.swing.JComboBox<String> jCbRefrescoSprite;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
