/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria_proyecto;

/**
 *
 * @author snakt
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtontelefono = new javax.swing.JButton();
        jButtonMostrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtontelefono.setText("Pedido por Teléfono");
        jButtontelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtontelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButtonMostrador.setText("Pedido por Mostrador");
        jButtonMostrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostradorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontelefonoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PedidoTelefono newFrame= new PedidoTelefono();
        newFrame.setVisible(true);
    }//GEN-LAST:event_jButtontelefonoActionPerformed

    private void jButtonMostradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostradorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PedidoMostrador newFrame= new PedidoMostrador();
        newFrame.setVisible(true);
    }//GEN-LAST:event_jButtonMostradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrador;
    private javax.swing.JButton jButtontelefono;
    // End of variables declaration//GEN-END:variables
}
