/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria_proyecto;

import BDD.ConexionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author snakt
 */
public class TicketMostrador extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form Ticket
     */
    CarpetaMenu pro= new CarpetaMenu();
    
    public TicketMostrador() {
        initComponents();
        String Cabecera[]={"Productos","Cantidad","Precio"};
        String Datos[][]={};
        modelo= new DefaultTableModel(Datos,Cabecera);
        jTTiket.setModel(modelo);
    }
    
    public ResultSet SeleccionarProdu(){
    Statement st;
    ResultSet rs=null;
        try {
            st=cn.createStatement();
            rs=st.executeQuery("Select * from menu");
        } catch (SQLException ex) {
            Logger.getLogger(PedidoTelefono.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rs;
    }
    
    
    public void MostrarProdu(){
    JTable tabla;
    ResultSet rs;
    DefaultTableModel dfm=new DefaultTableModel (){
    
    public boolean isCellEditable(int fila, int columna){
    return false;
      }
    };
    
    tabla=this.jTTiket;
    tabla.setModel(dfm);
    dfm.setColumnIdentifiers(new Object[] {"Producghjklñtos","Cantidad", "Precio"});
    rs=SeleccionarProdu();
    
    try {
        while(rs.next()){
            dfm.addRow(new Object[] {rs.getString("PizzaHM"), rs.getString("PizzaHG"), rs.getString("PizzaHF")});
        }   
    } catch (SQLException ex) {
            Logger.getLogger(TicketMostrador.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTTiket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnomCliente = new javax.swing.JTextField();
        jTextFieldPrecioT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonPagar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTTiket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 450, 80));

        jLabel1.setText("Folio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));
        getContentPane().add(jTextFieldFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, -1));

        jLabel2.setText("Nombre del Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jTextFieldnomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldnomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, -1));
        getContentPane().add(jTextFieldPrecioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 70, -1));

        jLabel4.setText("Precio Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        jTextFieldHora.setText("Hora");
        getContentPane().add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 60, -1));

        jTextFieldFecha.setText("Fecha");
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 60, -1));

        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 20, 20));

        jBGenerar.setText("Generar");
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomClienteActionPerformed

    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
        // TODO add your handling code here:
        /*String Pro;
        Pro = pro.PizzaHF;
        Object jTTiket[]={Pro};
        modelo.addRow(jTTiket);*/
    }//GEN-LAST:event_jBGenerarActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketMostrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketMostrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGenerar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTiket;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldFolio;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldPrecioT;
    private javax.swing.JTextField jTextFieldnomCliente;
    // End of variables declaration//GEN-END:variables
    
    ConexionDB cc= new ConexionDB();
    Connection cn= cc.conexion();
}
